baseurl = "https://atta-metta.net/"
languageCode = "en-us"
theme = "hyde-x"
title = "Metta"
disqusShortname = "attametta"
paginate = 5

[author]
  name = "Metta"

[params]
  theme = "theme-base-0e"
  highlight = "zenburn"

  tagline = "decentralized internets"

  googleAnalytics = "UA-45168329-1"
  truncate = false

  github = "https://github.com/atta-metta"

  rss = true

  # Optional additional custom CSS file URL, will override other styles.
  customCSS = "/css/overrides.css"

  # Default page metadata, used when the specific page doesn't set its own.
  defaultDescription = "Status updates on Metta development"
  defaultKeywords = "devlog,blog,metta,decentralised,peer-to-peer"

[permalinks]
  post = "/blog/:year/:month/:day/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
